dist:
  name: profiling-collector
  description: Profiling OTel Collector distribution
  output_path: ./collector
  otelcol_version: 0.109.0

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.109.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.109.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.109.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.109.0
  - gomod:
      github.com/open-telemetry/opentelemetry-ebpf-profiler v0.0.0-20240919060838-fafb6e25e998
    import: github.com/open-telemetry/opentelemetry-ebpf-profiler/otel/receiver
    name: profilingreceiver
