name: "CI-Rust"

on:
  push:
    branches: [main]
    paths:
      - rust-crates/**
      - Cargo.toml
      - Cargo.lock
  pull_request:
    branches: ["**"]
    paths:
      - rust-crates/**
      - Cargo.toml
      - Cargo.lock

permissions:
  contents: read

jobs:
  rust-test:
    name: Rust Tests (${{ matrix.target_arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - { target_arch: amd64, runner: ubuntu-24.04, rust_target: x86_64-unknown-linux-musl }
          - { target_arch: arm64, runner: ubuntu-24.04-arm, rust_target: aarch64-unknown-linux-musl }
    steps:
      - name: Clone code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust_target }}
          toolchain: 1.88.0
      - name: Install protoc
        uses: ./.github/workflows/protoc
      - name: Tests
        run: make rust-tests
